### ISSUE TITLE
Increase timeout to correspond to frame?

### ISSUE THREAD

**Issue by dy** [WebReflection/reraf#2]
Going to use that as a base for [wait-please](https://ghub.io/wait-please).
I wonder, would that make sense to emulate frame delay with FPS=60 in node?

**Comment by WebReflection** [comment]
the purpose is to schedule asynchronously ASAP, and ASAP in DOM is `requestAnimationFrame`, but in Node is actually nextTick, or maybe setImmediate.

As this library has really not much sense to exist in node, and it works in there only to be able to use it for tests and other stuff, the precision of the delay is absolutely irrelevant, as long as the task is scheduled asynchronously and, somehow, ASAP.

**Comment by WebReflection** [comment]
P.S. the two callbacks have different signature, so passing `1000/60` as second argument might require my attention if requestAnimationFrame suddenly accepts a second argument ... not kinda likely to happen, but another reason to simply keep it as is
